### ISSUE TITLE
The console displays an error

### ISSUE THREAD

**Issue by fedtv1452** [flaweoff/OfflineManager#3]
[22:05:48] [Server thread/ERROR]: Exception when MrIrbis attempted to tab complete om ec Sergey5588
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/om ec Sergey5588' in plugin OfflineManager v3.0.1-SNAPSHOT
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:231) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabCompleteCommand(CraftServer.java:1763) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabComplete(CraftServer.java:1735) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:573) ~[?:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PacketPlayInTabComplete.a(SourceFile:35) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NullPointerException
        at sun.reflect.GeneratedConstructorAccessor81.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.ForkJoinTask.reportException(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_301]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_301]
        at net.flawe.offlinemanager.data.memory.Storage.getListForComplete(Storage.java:114) ~[?:?]
        at net.flawe.offlinemanager.commands.ManagerCommand.onTabComplete(ManagerCommand.java:116) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[spigot.jar:git-Spigot-37d799b-3eb7236]
        ... 23 more

**Comment by flaweoff** [comment]
Check the logs for OfflineManager startup errors and, if there are any, leave them here. If there are no mistakes, then describe your actions that led to this. I need more information.

**Comment by flaweoff** [comment]
I have update the plugin. Check with new version 3.0.4
