### ISSUE TITLE
error null

### ISSUE THREAD

**Issue by argon000s** [flaweoff/OfflineManager#4]
Running any /om or /offlinemanager command on paper 1.18.1 OfflineManager v3.0.3-SNAPSHOT, command does not run and 

Edit: this happens on most but not all players

I get this error:
```
[22:16:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'om' in plugin OfflineManager v3.0.3-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2081) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-197]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-197]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.ReportedException: Loading entity NBT
        at net.minecraft.world.entity.Entity.load(Entity.java:2343) ~[paper-1.18.1.jar:git-Paper-197]
        at net.flawe.offlinemanager.api.util.v1_18_R1.data.PlayerData.<init>(PlayerData.java:90) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.api.util.v1_18_R1.data.PlayerData.<init>(PlayerData.java:77) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.api.util.v1_18_R1.data.PlayerData.<init>(PlayerData.java:73) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.api.util.v1_18_R1.NMSManager.getPlayerData(NMSManager.java:72) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.OfflineManager.getPlayerData(OfflineManager.java:193) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.commands.sub.ContainerCommand.execute(ContainerCommand.java:97) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.commands.ManagerCommand.onCommand(ManagerCommand.java:105) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.c(String, int)" because "nbt" is null
        at net.minecraft.world.entity.Entity.load(Entity.java:2178) ~[paper-1.18.1.jar:git-Paper-197]
        at net.flawe.offlinemanager.api.util.v1_18_R1.data.PlayerData.<init>(PlayerData.java:90) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.api.util.v1_18_R1.data.PlayerData.<init>(PlayerData.java:77) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.api.util.v1_18_R1.data.PlayerData.<init>(PlayerData.java:73) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.api.util.v1_18_R1.NMSManager.getPlayerData(NMSManager.java:72) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.OfflineManager.getPlayerData(OfflineManager.java:193) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.commands.sub.ContainerCommand.execute(ContainerCommand.java:97) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at net.flawe.offlinemanager.commands.ManagerCommand.onCommand(ManagerCommand.java:105) ~[OfflineManager.3.0.3-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

**Comment by flaweoff** [comment]
Most likely the player file is corrupted and the server cannot load it. Check the integrity of the player file.

**Comment by argon000s** [comment]
I'm getting this error on 99% of players, they cannot all be corrupted. Have you tested using paper? There is a possibility that other plugins I use are affecting this, I will try without any other plugins.

**Comment by flaweoff** [comment]
The problem is that the server itself returns null in the method that is responsible for getting the player's NBT tags. So far, I can't think of a solution to your problem.

**Comment by flaweoff** [comment]
Try with new version 3.0.4
It is available in releases on GitHub

**Comment by argon000s** [comment]
Yes, i am not getting this error any more, thanks.
